### ISSUE TITLE
HTTP ERROR 400 Bad header value for X-Forwarded-Port

### ISSUE THREAD

**Issue by srikanthkakumanu** [vortex-samples/debug-client-nodejs-shell#1]
Hi,

I am trying to use the vortex first time and configured the vortex as per the documentation, tried the vortex command as shown below. 
![image](https://user-images.githubusercontent.com/5272705/115563712-759eb080-a2d5-11eb-8964-c0bb9303550c.png)

But I received an error each time I try hitting the URL. I don't know why it is picking up 80 port number even when i passed 8787 as the port number. Just FYI, local app is running absolutely fine with 8787 port number.

![image](https://user-images.githubusercontent.com/5272705/115564241-ed6cdb00-a2d5-11eb-801d-8eb90f967791.png)

Here is the Journal entry for more details.

![image](https://user-images.githubusercontent.com/5272705/115564838-7ab02f80-a2d6-11eb-90c5-d3e4cbc0966b.png)

**Comment by vortex-samples** [comment]
Hi,

Thank you for informing us of the issue.  

The 80 value is for the x-forward-port of the original request so that it may properly route back a response after it is replayed to your local port of 8787. Looking at the output there is an additional : being prefixed prior to the proto and port, which shouldn't be there.

We haven't yet used or tested Jetty, but we'll create a test app and look into this further.  Not that is required, but if you are aware of a basic sample app that we could use to quickly stand up and test, we'll use it to investigate this issue.

Regards.

**Comment by vortex-samples** [comment]
Hi srikanthkakumanu,

Please give it a try now. We fixed the issue of the x-forwarded-proto and x-forwarded-port containing a prefixed :

Best Regards

![image](https://user-images.githubusercontent.com/58530957/115621632-cbb72800-a2c4-11eb-8956-f834b8bfb644.png)

**Comment by vortex-samples** [comment]
We are closing this issue since the the x-forwarded headers do not contain a colon, which caused the "Bad header value ..." in Jetty.

**Comment by srikanthkakumanu** [comment]
Sure. Let me try it again and let you know. Hope it works this time. Just FYI. This is not about Jetty. I am just testing webhooks for local Jenkins server to expose

**Comment by srikanthkakumanu** [comment]
Yes. It is working now. Thank you for resolving this issue.
